on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build/test/push (preview)
jobs:

  build:
    runs-on: ubuntu-latest
    name: build-${{ matrix.config.product}}

    environment: build-and-push

    strategy:
      fail-fast: false
      matrix:
        config:
          - {product: 'rstudio-workbench-preview', dir: 'server-pro', prefix: RSP, version: 'daily'}
          - {product: 'rstudio-workbench-preview', dir: 'server-pro', prefix: RSP, version: 'preview'}
          - {product: 'rstudio-connect-preview', dir: 'connect', prefix: RSC, version: 'daily'}
          - {product: 'rstudio-connect-content-init-preview', dir: 'connect-content-init', prefix: RSC, version: 'daily'}

    steps:
      # TODO: a way to get the preview version...
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Get version
        id: version
        run: |
          VERSION=`./get-version.py ${{ matrix.config.product }} --type=${{ matrix.config.version }}`
          echo "::set-output name=VERSION::${VERSION}"

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.config.dir }}
          file: ./${{ matrix.config.dir }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            rstudio/${{ matrix.config.product }}:${{ matrix.config.version }}
            rstudio/${{ matrix.config.product }}:${{ steps.version.outputs.VERSION }}
            ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.version }}
            ghcr.io/rstudio/${{ matrix.config.product }}:${{ steps.version.outputs.VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true
          push: false
          build-args: |
            RSP_VERSION=${{ steps.version.outputs.VERSION }}
            RSC_VERSION=${{ steps.version.outputs.VERSION }}
            RSPM_VERSION=${{ steps.version.outputs.VERSION }}
            RSP_DOWNLOAD_URL=https://s3.amazonaws.com/rstudio-ide-build/server/bionic/amd64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Test image
        env:
          IMAGE_NAME: rstudio/${{ matrix.config.product }}:${{ matrix.config.version }}
          # because we cannot dynamically set env var names... set them all...
          RSP_VERSION: ${{ steps.version.outputs.VERSION }}
          RSC_VERSION: ${{ steps.version.outputs.VERSION }}
          RSPM_VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          docker-compose -f ./${{ matrix.config.dir }}/docker-compose.test.yml run sut

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_PAT }}

      - name: Push image(s) to Docker Hub
        run: |
          docker push rstudio/${{ matrix.config.product }}:${{ matrix.config.version }}
          docker push rstudio/${{ matrix.config.product }}:${{ matrix.config.version }}
          docker push ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.version }}
          docker push ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.version }}
