on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

name: Build and Test (latest)
jobs:

  build:
    runs-on: ubuntu-latest
    name: r${{ matrix.config.r }} py${{ matrix.config.py }} ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          # at least one image containing the older versions
          - {r: '3.1.3', py: '2.7.18', os: 'ubuntu18.04'}
          - {r: '3.2.5', py: '2.7.18', os: 'ubuntu18.04'}
          - {r: '3.4.4', py: '3.6.13', os: 'ubuntu18.04'}
          - {r: '3.5.3', py: '3.7.10', os: 'ubuntu18.04'}
          # latest two R/Python are built with both sets of combinations
          - {r: '3.6.3', py: '3.8.8', os: 'ubuntu18.04'}
          - {r: '3.6.3', py: '3.9.2', os: 'ubuntu18.04'}
          - {r: '4.0.4', py: '3.8.8', os: 'ubuntu18.04'}
          - {r: '4.0.4', py: '3.9.2', os: 'ubuntu18.04'}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./connect-runtime/${{ matrix.config.os }}
          file: ./connect-runtime/${{ matrix.config.os }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            rstudio/rstudio-connect-runtime:r${{ matrix.config.r }}-py${{ matrix.config.py }}-${{ matrix.config.os }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.ref == 'refs/head/main' }}
          build-args: |
            R_VERSION=${{ matrix.config.r }}
            PYTHON_VERSION=${{ matrix.config.py }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
