on:
  # schedule:
  #   - cron: '0 8 * * *'
  push:
    branches:
      - dk/add-variants

name: build,test,push (preview)
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - uses: ./actions/single
        name: "build one"
        with:
          build_type: "release"
          package: "workbench"
          os: "bionic"
          RSPM_LICENSE: ${{ secrets.RSPM_LICENSE }}
          RSC_LICENSE: ${{ secrets.RSC_LICENSE }}
          RSW_LICENSE: ${{ secrets.RSW_LICENSE }}