on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build/test/push (latest)
jobs:

  build:
    runs-on: ubuntu-latest
    name: build-${{ matrix.config.tag_prefix}}${{ matrix.config.product}}

    # beware - several copies of matrix below
    strategy:
      fail-fast: false
      matrix:
        config:
          - {product: 'rstudio-workbench', dir: 'server-pro', prefix: RSP, version: 1.4.1717-3}
          - {product: 'rstudio-connect', dir: 'connect', prefix: RSC, version: 1.8.8.2}
          - {product: 'rstudio-package-manager', dir: 'package-manager', prefix: RSPM, version: 1.2.2.1-17}
          - {product: 'r-session-complete', tag_prefix: 'bionic-', dir: 'r-session-complete/bionic', prefix: RSP, version: 1.4.1717-3}
          - {product: 'r-session-complete', tag_prefix: 'centos7-', dir: 'r-session-complete/centos7', prefix: RSP, version: 1.4.1717-3}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.config.dir }}
          file: ./${{ matrix.config.dir }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}latest
            rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ matrix.config.version }}
            ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}latest
            ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ matrix.config.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true
          push: false
          build-args: |
            RSP_VERSION=${{ matrix.config.version }}

      - name: Test image
        env:
          IMAGE_NAME: rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ matrix.config.version }}
          # because we cannot dynamically set env var names... set them all...
          RSP_VERSION: ${{ matrix.config.version }}
          RSC_VERSION: ${{ matrix.config.version }}
          RSPM_VERSION: ${{ matrix.config.version }}
        run: |
          docker-compose -f ./${{ matrix.config.dir }}/docker-compose.test.yml run sut

      - name: Show image size
        run: |
          docker image ls

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_PAT }}

      - name: Push image(s) to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ matrix.config.version }}
          docker push rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}latest
          docker push ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ matrix.config.version }}
          docker push ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}latest
