on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Which images to build. Default 'all'. Options: 'all', 'workbench', 'package-manager', 'connct'"
        required: true
        default: "all"
      version:
        description: "The version to build. Default 'auto'. Can use any string, but must have which != 'all' if using something other than 'auto'"
        required: false
        default: "auto"
      os:
        description: "The os to build. Default 'all'. Options: 'all', 'bionic', 'jammy'"
        required: true
        default: "all"
      types:
        description: "The types to build. Default 'preview daily' . Options: 'preview', 'daily'"
        required: false
        default: "preview daily"

name: build,test,push (preview)
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.output.matrix }}
    steps:
      - uses: actions/checkout@v2

      - uses: extractions/setup-just@v1
      
      - name: Set Matrix
        id: set-matrix
        run: |
          MATRIX=$(jq -Mcr < just gm --types ${{ github.event.inputs.types }} --os ${{ github.event.inputs.os }} --packages ${{ github.event.inputs.packages }})
          echo "Raw Matrix: $MATRIX"
          echo "::set-output name=matrix::$MATRIX"




  build:
    runs-on: "ubuntu-latest"
    needs: matrix
    name: build-${{matrix.config.package}}-${{matrix.config.os}}-${{matrix.config.type}}

    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - name: Build Images (just)
        id: build-images
        run: |
          TAGS=`just b ${{ matrix.config.type }} ${{ matrix.config.package }} ${{ matrix.config.os }}`
          echo "::set-output name=tags::$TAGS"
        
      - name: Show Image Sizes
        run: |
          docker image ls

      - name: Test Images (just)
        id: test-images
        env:
          RSC_LICENSE: ${{ secrets.RSC_LICENSE }}
          RSPM_LICENSE: ${{ secrets.RSPM_LICENSE }}
          RSW_LICENSE: ${{ secrets.RSW_LICENSE }}
        run: |
          just t ${{ matrix.config.package }} ${{ steps.build-images.outputs.tags }}

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-rspm' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to ghcr.io
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-rspm' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_PAT }}

      - name: Push Images (just)
        id: push-images
        run: |
          just p ${{ steps.build-images.outputs.tags }}
      