on:
  schedule:
    # every morning at 8am UTC
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    - cron: "0 8 * * *"
  push:
    branches:
      - main
      - dev
      - dev-rspm
  pull_request:

name: build,test,push (preview) V2
jobs:
  build:
    runs-on: "ubuntu-latest"
    needs: matrix
    name: build-${{matrix.config.package}}-${{matrix.config.os}}-${{matrix.config.type}}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {package: "workbench", os: "bionic", type: "daily"}
          - {package: "workbench", os: "jammy", type: "daily"}
          - {package: "workbench", os: "bionic", type: "preview"}
          - {package: "workbench", os: "jammy", type: "preview"}
          - {package: "connect-content-init", os: "focal", type: "daily"}
          - {package: "package-manager", os: "bionic", type: "daily"}
          - {package: "r-session-complete", os: "bionic", type: "daily"}
          - {package: "r-session-complete", os: "centos7", type: "daily"}
          - {package: "r-session-complete", os: "bionic", type: "preview"}
          - {package: "r-session-complete", os: "centos7", type: "preview"}
    steps:
      - uses: actions/checkout@v2

      - uses: extractions/setup-just@v1

      - uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Images (just)
        id: build-images
        run: |
          TAGS=`just build ${{ matrix.config.type }} ${{ matrix.config.package }} ${{ matrix.config.os }} ${{ steps.buildx.outputs.name }}`
          echo "::set-output name=tags::$TAGS"

      - name: Show Image Sizes
        run: |
          docker image ls

      - name: Test Images (just)
        id: test-images
        env:
          RSC_LICENSE: ${{ secrets.RSC_LICENSE }}
          RSPM_LICENSE: ${{ secrets.RSPM_LICENSE }}
          RSW_LICENSE: ${{ secrets.RSW_LICENSE }}
        run: |
          just test-image ${{ matrix.config.type }} ${{ matrix.config.package }} ${{ steps.build-images.outputs.tags }}

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-rspm' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to ghcr.io
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-rspm' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_PAT }}

      - name: Push Images (just)
        id: push-images
        run: |
          just push-images ${{ steps.build-images.outputs.tags }}
