on:
  push:
    branches:
      - main
      - dev
  pull_request:

name: lint Dockerfiles
jobs:

  lint:
    runs-on: ubuntu-latest
    name: lint-${{ matrix.config.product }}-${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {product: 'workbench', os: 'bionic'}
          - {product: 'workbench', os: 'rockylinux8'}
          - {product: 'connect', os: 'bionic'}
          - {product: 'connect', os: 'rockylinux8'}
          - {product: 'connect-content-init', os: 'focal'}
          - {product: 'connect-content-init', os: 'rockylinux8'}
          - {product: 'package-manager', os: 'bionic'}
          - {product: 'package-manager', os: 'rockylinux8'}
          - {product: 'r-session-complete', os: 'bionic'}
          - {product: 'r-session-complete', os: 'rockylinux8'}
          - {product: 'r-session-complete', os: 'centos7'}
          - {product: 'workbench-for-microsoft-azure-ml', os: 'bionic'}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ${{ matrix.config.product }}/Dockerfile.${{ matrix.config.os }}
          config: ./hadolint.yaml
